name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Stable Flet 0.21.2
        run: |
          pip install flet==0.21.2 requests

      - name: Setup Flutter (MATCHING STABLE VERSION)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Build the APK (STABLE NATIVE AUDIO)
        run: |
          flet build apk --project devotional --org com.edu.devotional

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Daily-Devotional-App
          path: build/apk/**/*.apk
          retention-days: 3
